### ISSUE TITLE
client.multiUpsert() - creates/overwrites items for multiple tables in a batch

### ISSUE THREAD

**Issue by meaku** [epha/model#13]
Creates/overwrites items for multiple tables in a batch
- converts elements in array into proper `params` object
- has the same semantics as the version with a given table 

i.e. 

```javascript

client.multiUpsert({
   TableA: [],
   TableB: []
});

//=> batchWriteItems({ TableA: [], TableB: [] });

client.table("Example").multiUpsert([])

//=> batchWriteItems({ Example: [] });
```

TODO:
- [x] Implement multi Upsert methods
- [x] Add tests to ensure functionality

**Comment by flootr** [comment]
Amazons `batchWriteItem()` can only process 25 items at a time. If there are more than 25 items we will get an `ValidationException: Too many items requested for the BatchWriteItem call`.

At this time the logic to only do requests with 25 items is implemented in `client.table("tableName").upload()` which uses `client.table("tableName").multiUpsert()`.

The question is how to implement this properly and where to place the logic and to answer if `client.multiUpsert()` should handle this limitation or not.

**Comment by meaku** [comment]
It's implemented in `multiWriteItem`, right? We should add it to multiReadItem as well to be consistent. 
Maybe that's an option we could add to the client initialization whether the pagination should be handled automatically. There might be some cases you want still want to take control of. But maybe you should use the native `.dynamo` functions then. What do you think?

**Comment by flootr** [comment]
Tests aedb7d1518372309dd2c8c741dc6195952f7b832
