### ISSUE TITLE
Should not use delete as a function name

### ISSUE THREAD

**Issue by flootr** [epha/model#8]
We should not use `delete` as a function name because it is a reserved word in Javascript ES6. 
See https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Lexical_grammar#Keywords

We do so in `lib/sugar.js`. Will fix this tomorrow and rename it to `remove`.

**Comment by meaku** [comment]
:+1:

**Comment by flootr** [comment]
done 7c18900f06663051db71c2d7af6b3652cb06ea47
